### ISSUE TITLE
Raspberry Pi Monitoring dashboard not added to Grafana

### ISSUE THREAD

**Issue by danifr** [danifr/internet-pi#1]
Original message: https://github.com/geerlingguy/internet-pi/issues/226#issuecomment-922542108

@jimkuk, please make sure you follow this steps:

```
git clone https://github.com/danifr/internet-pi.git ~/internet-pi-danifr
cd ~/internet-pi-danifr
cp /path/to/original/internet-pi/config.yml ~/internet-pi-danifr/config.yml # copy your config.yml from the original internet-pi directory to internet-pi-danifr
ansible-playbook main.yml # run the playbook again
```

Let me know if you can see the dashboard after running those commands :)

**Comment by jimcuk** [comment]
ran the commands - not seeing the Dashboard?

**Comment by danifr** [comment]
OK, what do you see if you click on Search and then General? Do you see the Rasbperry Pi Monitoring dashboard there?

![image](https://user-images.githubusercontent.com/7135482/134047730-51e4d7bd-b197-47b1-ab9a-74aea34e173a.png)

Btw I just pushed a new fix to my branch, you might want to run:

```
cd ~/internet-pi-danifr
git pull --rebase origin rpi_monitoring
ansible-playbook main.yml
```

**Comment by jimcuk** [comment]
Just the internet connection

![image](https://user-images.githubusercontent.com/30991113/134049982-d572024e-2f7d-426c-9395-4a2f9b39e840.png)

**Comment by jimcuk** [comment]
getting this with the new fix
![image](https://user-images.githubusercontent.com/30991113/134050480-8d0e0eb5-6cf5-4262-b33b-097ac969414d.png)

**Comment by jimcuk** [comment]
ok didnt realise I had another inventory file to edit, I have done that and now get as far as

![image](https://user-images.githubusercontent.com/30991113/134054133-039dca57-9ee2-4205-aebc-f96fd12dc7a1.png)

**Comment by danifr** [comment]
Ah good, that looks way better.
Please manually create `/home/pi/raspberry-monitoring` and run the ansible playbook again:

```
mkdir /home/pi/raspberry-monitoring
ansible-playbook main.yml
```
I will add some ansible code to automatically create the directory in my next commit.

**Comment by jimcuk** [comment]
![image](https://user-images.githubusercontent.com/30991113/134056005-8ca07a4d-2b76-481c-8760-3e3159aeda78.png)

**Comment by jimcuk** [comment]
would I be right in thinking it is the init file that is missing ?
![image](https://user-images.githubusercontent.com/30991113/134057568-d929ff74-fb7e-41b8-bd95-edb461a19cb5.png)

**Comment by danifr** [comment]
Weird, I cannot reproduce your issue on my system. Let's do something, change the variable `config_dir` in
 the `config.yaml` to something like: `/tmp/new_directory`. Then run ansible again.

If it fails, can you please paste the error message and your `config.yaml`?

**Comment by jimcuk** [comment]
![image](https://user-images.githubusercontent.com/30991113/134065462-dc2a97e1-ec73-4c01-b48e-e03c7588e4d3.png)

![image](https://user-images.githubusercontent.com/30991113/134065685-80e19dc9-6b7c-403f-bb7d-e8afa1e6247c.png)

**Comment by danifr** [comment]
Please read the error message, you added an unnecessary extra line in your `config.yml` file (line 3)

try with:
`config_dir: '/tmp/new_directory'`

(everything that starts with a `#` is commented out)

**Comment by jimcuk** [comment]
yeah sorry dont know what I was thinking there.
made the correction but still getting the error below
![image](https://user-images.githubusercontent.com/30991113/134069347-7f4792ca-fd3f-4d8b-8c81-212b3a774185.png)

**Comment by danifr** [comment]
Np!

I wonder if there is a permission issue related to your user... anyway, let's create those directories manually.
```
mkdir /tmp/new_directory/raspberry-monitoring/data
mkdir /tmp/new_directory/raspberry-monitoring/init
```
Then run the ansible playbook again.

**Comment by jimcuk** [comment]
Ok I had just created the init directory before you posted and now have the monitoring appear in grafana 
without data - guessing the data directory will solve that - off to check

**Comment by jimcuk** [comment]
yip that is it up and running. Great stuff.
Many thanks for your tima and patience Daniel

**Comment by danifr** [comment]
No problem! Happy it is finally working! In the coming days, I will add some ansible code to make sure those 2 directories exist.
Thanks to you for all your tests!

**Comment by jimcuk** [comment]
Hi danifr
what steps would be necessary to add another pi to the grafana monitoring?
