### ISSUE TITLE
How to add docker container into existing instance

### ISSUE THREAD

**Issue by psylion** [danifr/internet-pi#5]
Hi @danifr,
I'm interesting to do the same things adding the RPI into the Jeff internet-monitoring.

But I already had struggles to configure additional ICMP ping into my Grafana instances.
Now looking at the RPI / telegraf / influxdb... I had already 2 days configuring the stuff... without success.
I just realize that I didn't take into account the fact that the initial solution is using docker... Then I try ti install telegraf manually in my system... newbie error... or old fashion habits.

I'm looking for a way to do the same thing has you did but inside my existing instance. I would like to avoid making a second docker instance if I get it from your git.
Can you help my by providing some guidance or nice article which will be useful to sort this out?

Cheers from Belgium

**Comment by danifr** [comment]
Hi @psylion,

I am not sure if I understand your question. My changes are made on top on Jeff's so no need to create a second instance.
If you want to use my changes you can do something like:

```
cd /path/to/your/internet-pi
git remote add danifr https://github.com/danifr/internet-pi.git
git fetch danifr
git checkout main
ansible-playbook main.yml 
```
Wait for ansible to do its magic and, voila! you will see a couple of new dashboards in grafana, one for pihole and the other other one for the raspberry pi host metrics.

Hope this helps :)

**Comment by psylion** [comment]
Whoua soo simple... I didn´t expect that
What about my changes in my local?
Do I need to copy my changes for backup . Is Thérèse risque of losing my staff?

**Comment by danifr** [comment]
Sure. To keep your existing changes just exec:
```
cd /path/to/your/internet-pi
git commit -am "psylion changes"
```
and then all run the commands I mentioned before. All your changes should be locally applied on top of mine.

Let me know if that worked for you.

**Comment by psylion** [comment]
Great thank you.
Indeed I forget that there are coming from github and this enable the local commit of changes.

Another concerns about the internet-monitoring folder:
Their is not git repo in that folder. Do i need to init or my changes their will not be affected?

**Comment by psylion** [comment]
Here is my feedback follow today actions:
- I followed your instructions and I can run it;
- but I lost some of the element which I configure in  the folder internet-monitoring/prometheus/..
- I added a pingICMP.yaml which is not loaded on the reload following the ansible-playbook
- I have tried to reload my config from the folder internet-monitoring with the cmd sudo docker-compose pull && sudo docker-compose up -d --force-recreate
 then I loose the new dashboard in grafana...
It looks like that I need to modify a bit more the local instance to apply your changes ... (raspberry-monitoring)

If you have suggestions, please you are welcome

another remark:
I change my docker-compose.yml in the internet-monitoring to use a different port 3131 in place of default 3030...
Which is set to default when I apply the ansible-playbook cmd

**Comment by psylion** [comment]
Haaa
i finally figured out
- I manage to modify tasks / templates for my needs
- and now i only use the ansible-playbook and don't need to reload docker containers.
just a remarks... I got sometimes my PI not responding and need an hard reset to reload

Thanks for your advices

**Comment by danifr** [comment]
Good to know! Glad it worked for you! :)
